version: '3.3'

services:
  oracle:
    image: xrdj6c/oracle-11g-xe
    container_name: oracle
    networks:
      - backend
    ports:
      - "1521:1521"
      - "8081:8080"
    restart: always
    environment:
      ORACLE_ALLOW_REMOTE: "true"
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    networks:
      - backend
    ports:
      - "8080:8080"
    restart: always
networks:
  backend:
    driver: bridge

